[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:Pandas requires version '2.8.4' or newer of 'numexpr':UserWarning
    ignore:Pandas requires version '1.3.6' or newer of 'bottleneck':UserWarning
