"""Canonical feature keys for CompanyState snapshots."""

FEATURE_KEYS = [
    # capital return
    "capital_return.buyback_capacity_proxy",
    "capital_return.share_count_trend",
    "capital_return.dividend_payer_flag",
    "capital_return.last_dividend_event_type",
    # liquidity
    "liquidity.cash",
    "liquidity.revolver_undrawn",
    "liquidity.liquidity_total",
    "liquidity.runway_months",
    "liquidity.minimum_cash_policy_proxy",
    "liquidity.available_for_actions",
    # capital structure
    "capital_structure.total_debt",
    "capital_structure.net_debt",
    "capital_structure.net_leverage",
    "capital_structure.gross_leverage",
    "capital_structure.interest_coverage",
    "capital_structure.maturity_wall_ratio_24m",
    "capital_structure.refi_pressure_flag",
    # market
    "market.market_cap",
    "market.enterprise_value",
    "market.ev_ebitda",
    "market.ev_ebitda_vs_peer_z",
    "market.conglomerate_discount_signal",
    "market.fcf_yield",
    "market.fcf_yield_percentile_peers",
    "market.pe_ratio",
    "market.pe_percentile_peers",
    "market.pe_percentile_history",
    "market.volatility_30d",
    "market.volatility_90d",
    "market.drawdown_90d",
    # expectations
    "expectations.analyst_coverage_count",
    "expectations.revision_signal",
    "expectations.eps_consensus_fy1",
    "expectations.revenue_consensus_fy1",
    "expectations.ebitda_consensus_fy1",
    "expectations.eps_revision_score_90d",
    "expectations.revenue_revision_score_90d",
    "expectations.ebitda_revision_score_90d",
    # macro
    "macro.sp500_pe_ttm",
    "macro.sp500_pe_ttm_percentile_history",
    "macro.us10y_treasury_yield",
    "macro.us10y_treasury_yield_percentile_history",
    "macro.us_ig_oas",
    "macro.us_ig_oas_percentile_history",
    "macro.us_hy_all_in_yield",
    "macro.us_hy_all_in_yield_percentile_history",
    "macro.real_gdp_growth_yoy",
    "macro.real_gdp_growth_yoy_percentile_history",
    # operating
    "operating.ebitda_margin_ttm",
    "operating.ebitda_margin_percentile_peers",
    "operating.fcf_conversion",
    "operating.segment_margin_divergence",
    "operating.revenue_yoy_last_q",
    "operating.ebitda_margin_trend_8q",
    "operating.margin_volatility_8q",
    "operating.revenue_cagr_3y",
    # ownership/governance
    "ownership_governance.top5_holder_pct",
    "ownership_governance.institutional_pct",
    "ownership_governance.holder_count_13f",
    "ownership_governance.crowding_signal",
    "ownership_governance.activist_signal",
    "ownership_governance.activist_presence_flag",
    # strategic
    "strategic.intent.return_capital_priority",
    "strategic.intent.deleveraging_priority",
    "strategic.intent.pursue_mna_priority",
    "strategic.intent.focus_on_core",
    "strategic.intent.restructure",
    "strategic.segment_count",
    "strategic.segment_references",
    # peer context
    "peer_context.peer_actions_rate",
    "peer_context.action_rate_percentile",
    "peer_context.action_rate_z",
    "peer_context.action_rate_band",
    "peer_context.action_rate_percentile",
    "peer_context.action_rate_band",
    "peer_context.valuation_percentile",
    "peer_context.leverage_percentile",
    "peer_context.margin_percentile",
    "peer_context.valuation_z",
    "peer_context.leverage_z",
    "peer_context.margin_z",
    "peer_context.valuation_band",
    "peer_context.leverage_band",
    "peer_context.margin_band",
    "peer_context.relative_positioning.market_share_percentile",
]
