from __future__ import annotations


# Shared "fast but still useful" SEC XBRL tag universe for financial-fact refreshes.
# This is intentionally broader than the original minimal fast set so we don't
# drop the very liquidity/debt concepts we care about for company-state metrics.
FINANCIAL_FACT_TAGS = {
    "Revenue",
    "Revenues",
    "SalesRevenueNet",
    "RevenueFromContractWithCustomerExcludingAssessedTax",
    "GrossProfit",
    "CostOfRevenue",
    "EBITDA",
    "OperatingIncome",
    "OperatingIncomeLoss",
    "IncomeLossFromContinuingOperations",
    "NetIncome",
    "NetIncomeLoss",
    "EarningsPerShareBasic",
    "EarningsPerShareDiluted",
    "Assets",
    "Liabilities",
    "StockholdersEquity",
    "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    "Cash",
    "CashAndCashEquivalentsAtCarryingValue",
    "CashAndCashEquivalentsPeriodIncreaseDecrease",
    "RestrictedCash",
    "RestrictedCashAndCashEquivalents",
    "RestrictedCashAndCashEquivalentsAtCarryingValue",
    "RestrictedCashAndCashEquivalentsCurrent",
    "RestrictedCashAndCashEquivalentsNoncurrent",
    "RestrictedCashAndInvestmentsNoncurrent",
    "MarketableSecurities",
    "MarketableSecuritiesCurrent",
    "ShortTermInvestments",
    "TradingSecuritiesShortTermInvestmentsAmortizedCost",
    "CashAndShortTermInvestments",
    "CashCashEquivalentsAndShortTermInvestments",
    "UnusedCommitmentUnderLineOfCreditFacility",
    "UnusedCommitmentUnderRevolvingCreditFacility",
    "AvailableBorrowingsUnderLineOfCreditFacility",
    "LineOfCreditFacilityMaximumBorrowingCapacity",
    "LineOfCreditFacilityAmountOutstanding",
    "LineOfCredit",
    "DebtCurrent",
    "ShortTermDebt",
    "DebtLongTerm",
    "LongTermDebt",
    "SharesOut",
    "Capex",
    "OperatingCashFlow",
    "NetCashProvidedByUsedInOperatingActivities",
    "NetCashProvidedByUsedInInvestingActivities",
    "NetCashProvidedByUsedInFinancingActivities",
    "InterestExpense",
    "CurrentAssets",
    "CurrentLiabilities",
    "CashDividends",
    "CommonStockDividendsPerShareCashPaid",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect",
}
